export const GET_MEMBER_LISTS_REQUEST = 'GET_MEMBER_LISTS_REQUEST'
export const GET_MEMBER_LISTS_SUCCESS = 'GET_MEMBER_LISTS_SUCCESS'
export const GET_MEMBER_LISTS_FAILURE = 'GET_MEMBER_LISTS_FAILURE'
